site_name: Manual de Usuario NazanUtility
nav:
    - Inicio: home.md
    - Panel de control: dahsboar.md
    - Tienda: store.md
    - Bancos: banks.md
    - Regiones: regions.md
    - registros: crud.md
theme: readthedocs  